version: "3.8"

services:
  db:
    image: postgres:15
    container_name: phoenix-postgres
    environment:
      POSTGRES_DB: phoenixdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: phoenix-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phoenixdb
      SPRING_DATASOURCE_USERNAME: youruser
      SPRING_DATASOURCE_PASSWORD: yourpass
    ports:
      - "8080:8080"

volumes:
  pgdata:
