services:
  db:
    image: postgres:12
    container_name: phoenix-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phoenix-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /code

volumes:
  pgdata:
