services:
  db:
    image: postgres:12
    container_name: phoenix-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: phoenix-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
    command: server /data
    volumes:
      - miniodata:/var/lib/minio/data

  backend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phoenix-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "${BACKEND_PORT}:8080"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /code
  
  frontend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phoenix-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app

volumes:
  pgdata:
  miniodata:
