spring:
  application:
    name: phoenix

  security:
    user:
      name: admin
      password: secret

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    loggers: [slf4j]

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: Phoenix
    description: Phoenix is a cloud application.
    version: 1.0.0

jwt:
  secret: ${jwt_secret}
  expiration: 3600

security:
  publicEndpoints:
    - /auth/login
    - /users/user
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /swagger-resources/**
    - /webjars/**